### ISSUE TITLE
Chart Component shows no data 

### ISSUE THREAD

**Issue by N00172468** [eoanodea/IADTY3PPClientMangementSystem#10]
When you load the page the chart component is populated with data, however, if you leave that page and go back, the chart component is empty.

**Comment by eoanodea** [comment]
On the mount of the component, it only structured the tasks after fetching from store, which was only done if tasks did not already exist in the VueX store. To fix added an else statement to the below code getting it to call the structureTasks function 

```
if(this.serviceId && this.tasks.length < 1) {
  this.$store.dispatch('task/loadTasks', [this.serviceId, true])
  .then(() => this.structureTasks())
}
```
